//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VC_forms> VC_forms { get; set; }
        public virtual DbSet<VC_formTableName> VC_formTableName { get; set; }
        public virtual DbSet<VC_identity> VC_identity { get; set; }
        public virtual DbSet<VC_roles> VC_roles { get; set; }
        public virtual DbSet<VC_users> VC_users { get; set; }
    }
}
