//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_forms_tableNames
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int SW_formsId { get; set; }
    
        public virtual SW_forms SW_forms { get; set; }
    }
}
