//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Designer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VC_users
    {
        public int Id { get; set; }
        public string fullName { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int VC_rolesId { get; set; }
    
        public virtual VC_roles VC_roles { get; set; }
    }
}
