// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Graph.Models;
using System;
using System.Collections.Generic;
using VC_IMS.Models;

namespace VC_IMS.Models;

public partial class VC_IMSDb_moreContext : DbContext
{
    public VC_IMSDb_moreContext(DbContextOptions<VC_IMSDb_moreContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VC_identity> VC_identities { get; set; }

    public virtual DbSet<VC_form> VC_forms { get; set; }

    public virtual DbSet<VC_formProcess> VC_formProcesses { get; set; }

    public virtual DbSet<VC_formReport> VC_formReports { get; set; }

    public virtual DbSet<VC_formTableData_Type> VC_formTableData_Types { get; set; }

    public virtual DbSet<VC_formTableDatum> VC_formTableData { get; set; }

    public virtual DbSet<VC_formTableName> VC_formTableNames { get; set; }

    public virtual DbSet<VC_storedProcess> VC_storedProcesses { get; set; }

    public virtual DbSet<VC_storedProcessParam> VC_storedProcessParams { get; set; }

    public virtual DbSet<VC_reports> VC_reports { get; set; }

    public virtual DbSet<VC_reportParam> VC_reportParams { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VC_identity>(entity =>
        {
            entity.ToTable("VC_identity");
            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<VC_form>(entity =>
        {
            entity.HasIndex(e => e.VC_identityId, "IX_FK_VC_identityVC_forms");
            entity.Property(e => e.dateModified).HasColumnType("datetime");
            entity.Property(e => e.name).IsRequired();
            entity.HasOne(d => d.VC_identity).WithMany(p => p.VC_forms)
                .HasForeignKey(d => d.VC_identityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VC_identityVC_forms");
        });

        modelBuilder.Entity<VC_formProcess>(entity =>
        {
            entity.Property(e => e.url).IsRequired();
        });

        modelBuilder.Entity<VC_formReport>(entity =>
        {
            entity.ToTable("VC_formReport");
            entity.HasIndex(e => e.VC_formsId, "IX_FK_VC_formsVC_formReport");
            entity.Property(e => e.url).IsRequired();
            entity.HasOne(d => d.VC_forms).WithMany(p => p.VC_formReports)
                .HasForeignKey(d => d.VC_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VC_formsVC_formReport");
        });

        modelBuilder.Entity<VC_formTableData_Type>(entity =>
        {
            entity.HasIndex(e => e.VC_formsId, "IX_FK_VC_formsVC_formTableData_Types");
            entity.HasOne(d => d.VC_forms).WithMany(p => p.VC_formTableData_Types)
                .HasForeignKey(d => d.VC_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VC_formsVC_formTableData_Types");
        });

        modelBuilder.Entity<VC_formTableDatum>(entity =>
        {
            entity.HasIndex(e => e.VC_formsId, "IX_FK_VC_formsVC_formTableData");
            entity.HasOne(d => d.VC_forms).WithMany(p => p.VC_formTableData)
                .HasForeignKey(d => d.VC_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VC_formsVC_formTableData");
        });

        modelBuilder.Entity<VC_formTableName>(entity =>
        {
            entity.ToTable("VC_formTableName");
            entity.HasIndex(e => e.VC_formsId, "IX_FK_VC_formsVC_formTableName");
            entity.HasOne(d => d.VC_forms).WithMany(p => p.VC_formTableNames)
                .HasForeignKey(d => d.VC_formsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VC_formsVC_formTableName");
        });

        modelBuilder.Entity<VC_storedProcess>(entity =>
        {
            entity.ToTable("VC_storedProcess");
            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.Description).HasMaxLength(1024);
            entity.Property(e => e.ConnectionKey).HasMaxLength(128);
            entity.Property(e => e.DataSource).HasMaxLength(256);
            entity.Property(e => e.Database).HasMaxLength(256);
            entity.Property(e => e.DbUserEncrypted).HasMaxLength(512);
            entity.Property(e => e.DbPasswordEncrypted).HasMaxLength(1024);
            entity.Property(e => e.DbPasswordEncrypted).HasMaxLength(1024);
            entity.HasMany(e => e.Params)
                  .WithOne(p => p.StoredProcess)
                  .HasForeignKey(p => p.StoredProcessId)
                  .OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<VC_storedProcessParam>(entity =>
        {
            entity.ToTable("VC_storedProcessParam");
            entity.Property(e => e.Key).HasMaxLength(128);
            entity.Property(e => e.DataType).HasMaxLength(64);
        });

        modelBuilder.Entity<VC_reports>(entity =>
        {
            entity.ToTable("VC_reports");
            entity.HasKey(x => x.Id);
            entity.Property(x => x.Name).IsRequired().HasMaxLength(256);
            entity.Property(x => x.Desc).HasMaxLength(512);
            entity.Property(x => x.PathOverride).HasMaxLength(256);
            entity.Property(x => x.RoleId).IsRequired();
            entity.Property(x => x.ParamCheck).HasDefaultValue(false);
        });


        modelBuilder.Entity<VC_reportParam>(entity =>
        {
            entity.ToTable("VC_reports_params");
            entity.HasKey(x => x.Id);
            entity.Property(x => x.ParamKey).IsRequired().HasMaxLength(128);
            entity.Property(x => x.ParamValue).IsRequired().HasMaxLength(1024);
            entity.Property(x => x.ParamDataType).HasMaxLength(32);
            entity.HasOne(x => x.VC_report)
            .WithMany(r => r.Params)
            .HasForeignKey(x => x.VCReportId)
            .OnDelete(DeleteBehavior.Cascade);

        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}