// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VC_IMS.Models;

public partial class VC_formTableName
{
    public int Id { get; set; }

    public string name { get; set; }

    public string field { get; set; }

    public int VC_formsId { get; set; }

    public virtual VC_form VC_forms { get; set; }
}