// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VC_IMS.Models.Logging;
using System;
using System.Collections.Generic;

namespace VC_IMS.Models;

public partial class VC_form
{
    public int Id { get; set; }

    public string uuid { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public string form { get; set; }

    public DateTime dateModified { get; set; }

    public int VC_identityId { get; set; }

    public bool? is_linking { get; set; }

    public string image { get; set; }

    public string header { get; set; }

    public int? approvalAmt { get; set; }

    public virtual ICollection<VC_formReport> VC_formReports { get; set; } = new List<VC_formReport>();

    public virtual ICollection<VC_formTableDatum> VC_formTableData { get; set; } = new List<VC_formTableDatum>();

    public virtual ICollection<VC_formTableData_Type> VC_formTableData_Types { get; set; } = new List<VC_formTableData_Type>();

    public virtual ICollection<VC_formTableName> VC_formTableNames { get; set; } = new List<VC_formTableName>();

    public virtual VC_identity VC_identity { get; set; }
}