// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VC_IMS.Models;

public partial class VC_formProcess
{
    public int Id { get; set; }

    public string url { get; set; }

    public string name { get; set; }

    public int VC_formsId { get; set; }

}