// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VC_IMS.Models;

public partial class VC_identity
{
    public int Id { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public string logo { get; set; }

    public string media_01 { get; set; }

    public string media_02 { get; set; }

    public string media_03 { get; set; }

    public string header { get; set; }

    public string signature { get; set; }

    public virtual ICollection<VC_form> VC_forms { get; set; } = new List<VC_form>();
}